
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class LogInForm extends javax.swing.JFrame {

    Connection con;
    SqlQueries lms = new SqlQueries();
    
    public LogInForm() {
        initComponents();
        db.createTable();
        changeIcon();
        txtusername.setBackground(new java.awt.Color(0,0,0,1));
        txtpassword.setBackground(new java.awt.Color(0,0,0,1));
    }
    
    public void changeIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Resources/Frame-Logo.png")));
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblsignup = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblShowPassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnsignin = new javax.swing.JLabel();
        btnexit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(138, 102, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(226, 200, 171));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("password:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 140, 50));

        lblsignup.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblsignup.setText("Sign up?");
        lblsignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsignupMouseExited(evt);
            }
        });
        jPanel2.add(lblsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 80, 40));

        txtusername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtusername.setBorder(null);
        txtusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 380, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fields.png"))); // NOI18N
        jLabel5.setText("jLabel3");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 140, 430, 64));

        lblShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/show password.png"))); // NOI18N
        lblShowPassword.setText("jLabel3");
        lblShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPasswordMouseClicked(evt);
            }
        });
        jPanel2.add(lblShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 60, 40));

        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtpassword.setBorder(null);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 330, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fields.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 260, 430, 64));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("username:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 140, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Logo.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 100));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 860, 100));

        btnsignin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnsignin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnsignin.setText("Login");
        btnsignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsigninMouseClicked(evt);
            }
        });
        jPanel2.add(btnsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 90, 40));

        btnexit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnexit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnexit.setText("   Exit");
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        jPanel2.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 90, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonborder.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 90, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonborder.png"))); // NOI18N
        jLabel8.setText("jLabel7");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 90, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupMouseEntered
        String underln = "<html><u>Sign up?</u></html>";
        lblsignup.setText(underln);
        lblsignup.setForeground(Color.RED);
    }//GEN-LAST:event_lblsignupMouseEntered

    private void lblsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupMouseExited
        lblsignup.setText("Sign up?");
        lblsignup.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblsignupMouseExited

    private void lblsignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsignupMouseClicked
        new SignUpForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblsignupMouseClicked

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        signin();
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void lblShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPasswordMouseClicked
        char c = txtpassword.getEchoChar();
        if(c == '*'){
            txtpassword.setEchoChar((char) 0);
            lblShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/hide password.png")));
        }else{
            txtpassword.setEchoChar('*');
            lblShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/show password.png")));
        }
        
    }//GEN-LAST:event_lblShowPasswordMouseClicked

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        int ex = JOptionPane.showConfirmDialog(null, "Confirm exit?", "exit", JOptionPane.OK_CANCEL_OPTION);
        if(ex == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitMouseClicked

    private void btnsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMouseClicked
        signin();
    }//GEN-LAST:event_btnsigninMouseClicked
    
    private void signin(){
        String username = txtusername.getText();
        String password = txtpassword.getText();
        String user[] = lms.signIn(username, password);
        
        if(user == null){
            JOptionPane.showMessageDialog(null, "invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
            txtusername.setText("");
            txtpassword.setText("");
            txtusername.requestFocus();
        }else{
            if(user[4].equals("DEACTIVATED")){
                JOptionPane.showMessageDialog(null, "account deactivated. Contact an admin to reactivate your account", "Error", JOptionPane.ERROR_MESSAGE);
                txtusername.setText("");
                txtpassword.setText("");
                txtusername.requestFocus();
                return;
            }
            JOptionPane.showMessageDialog(null, "login successful as " + user[1], "Success", JOptionPane.PLAIN_MESSAGE);
            int id = Integer.parseInt(user[0]);
            if(user[3].equals("Student")){
                new UserPage(id, user[1], user[2]).setVisible(true);
            }
            else{
                new AdminPage(id, user[1], user[2]).setVisible(true);
            }
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnexit;
    private javax.swing.JLabel btnsignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblShowPassword;
    private javax.swing.JLabel lblsignup;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
